### ISSUE TITLE
Truncate with foreign key checks

### ISSUE THREAD

**Issue by TitanNano** [jerometwell/pynonymizer#22]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to truncate a table and also delete all associated data with it. We would like to truncate e.g. a customer table and have to also remove all associated data in other tables.

**Describe the solution you'd like**
Provide an additional table strategy which truncates with foreign key checks enabled.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by jerometwell** [comment]
Hi!  There is already a truncate table strategy, does this work for you?

https://github.com/jerometwell/pynonymizer/blob/master/doc/strategyfiles.md#table-strategy-truncate

**Comment by jerometwell** [comment]
If i understand what you're trying to achieve ( cascading delete) then `TRUNCATE` won't work anyway. 
IIRC truncate isn't suitable for tables with foreign keys. 
You'd need a `DELETE` statement. Is this a feature you need?

As a workaround, you could add this as a before script:
```
scripts:
  before:
    - DELETE FROM table;
```

**Comment by TitanNano** [comment]
@jerometwell yes you are correct, `TRUNCATE` doesn't actually work with foreign keys. The before script works, but an official table strategy would be more handy I think.

**Comment by jerometwell** [comment]
@TitanNano in this scenario, would you have foreign key checks with `CASCADE` enabled? or were you implying that pynonymizer should do discovery also? 

I'm just writing documentation and i want to be sure on the use-case. 

I've started PR #23 for this issue. If you could take a look at the implementation I'd appreciate a second pair of eyes.

**Comment by TitanNano** [comment]
@jerometwell yes `CASCADE` is enabled in our scenario. I will have a look at your WIP.

**Comment by jerometwell** [comment]
This change has been merged into `master` and should go out with `v1.13.0` - please test and report back if you can!

**Comment by TitanNano** [comment]
@jerometwell the new table strategy works as expected / described.
