### ISSUE TITLE
Cannot find module during import.

### ISSUE THREAD

**Issue by HenkWillcock** [jerometwell/pynonymizer#28]
I'm installing pynonymizer with pip, and including it as part of a larger project. My project includes a `tests` python package on the top level, the same as pynonymizer. This causes an issue where I can't import my `tests` package, because it gets confused with the pynonymizer one.

Since the `tests` package isn't needed to run pynonymizer (it's just for testing), could it be excluded from the pip package to avoid this issue?

Thanks.

**Comment by jerometwell** [comment]
Incidentally I think this is actually because of `tests/__init__.py` rather than the presence of the tests folder itself. 

But i'm in favour of controlling what goes into the package better! I think we can do this with an exclude parameter in setup.py, Can you help put together a PR?

**Comment by HenkWillcock** [comment]
Yes I can help, don't have any experience with using `setup.py` though.

**Comment by HenkWillcock** [comment]
https://github.com/jerometwell/pynonymizer/pull/29/files

I think this should do the trick, but am open to other suggestions.

**Comment by jerometwell** [comment]
Awesome. This change will be going out with v1.15.0 - please check and report back if you can 😇
