### ISSUE TITLE
Invoke pynonymizer programmatically

### ISSUE THREAD

**Issue by taffit** [jerometwell/pynonymizer#30]
**Is your feature request related to a problem? Please describe.**
pynonymizer does normally exactly what is needed, i. e. anonymize certain columns/drop data using a pre-defined, clear strategy-file. However it still needs a lot of parameters, especially if you use all the features, e. g. starting from a certain step, skipping another one etc. If it would be possible to invoke it programmatically, you could integrate it into your own workflow. For instance, I already have a commandline tool for my app that does already a lot of things (e. g. running an alembic migration, reset the database, adding seeding data etc.). The user/developer wouldn't need to learn another tool but can run the tool with the command she is used to.

**Describe the solution you'd like**
Honestly I don't know exactly what would be the best method. Probably some `pynonymizer`-object, to which you can assign a configuration/strategy-file (or having both in a single file). Then, once it is configured, you can just invoke `pynonymizer.run()` or similar and it does its job. Something like:
```python
a = Pynonymizer()
a.config_file = os.path.join('./myconfigfile.yml')
# Assuming the strategy-file is provided already in the config
# Now configuring the steps
a.config.start_at(ANONYMIZE_DB)
a.config.skip_step([DUMP_DB, DROP_DB])
# Getting some config from an environment variable
a.config.db_password = os.environ["DB_PASSWRD"]
# Another setting is provided via the arguments of my commandline tool which uses click
a.config.db_user = click.parameters.get("my_user", default_user)  # not real code here

# Doing a final check before running
is_all_needed_config_data_available = a.config.check()
if is_all_needed_config_data_available == True:
    result = a.run()
    if result.error_code != 0:
        print(f"Something happened: {result.message}")
```

**Describe alternatives you've considered**
Invoking the tool from within your code like you would invoke another executable is, of course, possible, but it doesn't give you that amount of control or integration that you would have when invoking from Python directly.

**Additional context**
Great library, really, a deeply felt "Thank you!"

**Comment by taffit** [comment]
I beg your pardon: After taking a closer look at your code, I saw that this is already largely possible. You just invoke the `pynonymizer.pynonimize()`-method, providing all the configuration there. The only suggestion would be to separate configuration from the actual invocation. This way you can define more specifically what should be done where, e. g. arguments provided on the commandline could overwrite settings provided by environment variables or the strategy-file or providing simple YML-instructions for truncating a table or ....

**Comment by taffit** [comment]
Sorry for not checking and thinking before.

**Comment by jerometwell** [comment]
I think a good takeaway here is that this information isn't exactly in the documentation or easily discoverable. I think we could do more to document this interface and add some convience features to make it more _pythonic_, since everything is oriented around the CLI, as you say. 

My suggestions might be:
* config-as-code / a contract for giving the strategyfiles and config as python objects
* convenience methods for common options/common combos
* feedback hooks / callbacks

I'm open to any other suggestions here. I'd like to re-open this to discuss the future of the programmatic interface, if that's cool with you?

**Comment by taffit** [comment]
Yes @jerometwell , sounds good to me. Having checked the code, I saw that it is quite straightforward to do what I wanted. Having some convenience functions / objects would be nonetheless helpful, as it opens up more possibilities without having to implement it yourself.

**Comment by jerometwell** [comment]
OK ! So i added some really rudimentary documentation comprising basically what we've discussed here. 
See 52196ae1ad576edc15f967a2b02b722cb049ce3c 😅

I'm going to close this issue, and create some more issues to track the individual things I had in mind. I'm glad you found what you needed ✨

**Comment by jerometwell** [comment]
I've created #31, #32 & #33 to cover this.
