### ISSUE TITLE
Error with v1.18.0: `NameError: name 'logger' is not defined`

### ISSUE THREAD

**Issue by dmaicher** [jerometwell/pynonymizer#54]
**Describe the bug**
With v1.18.0 I get an error when I want to run it:

```
Traceback (most recent call last):
  File "/usr/local/bin/pynonymizer", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/pynonymizer/cli.py", line 161, in cli
    _warn_deprecated_env("DB_HOST", "PYNONYMIZER_DB_HOST")
  File "/usr/local/lib/python3.9/site-packages/pynonymizer/cli.py", line 123, in _warn_deprecated_env
    logger.warning("Environmental var $%s is deprecated. Use $%s", old_env, new_env)
NameError: name 'logger' is not defined
```

**To Reproduce**
My Dockerfile looks like this

```
FROM python:3.9-slim

RUN pip install pynonymizer \
    && apt-get update \
    && apt-get install default-mysql-client -y
```

**Expected behavior**
It should work like with version 1.17.0 I guess

**Comment by jerometwell** [comment]
Ola, just to be clear (for my testing sanity also), you're using the deprecated positional arg `DB_HOST` right?

**Comment by dmaicher** [comment]
Well actually to be fair I'm running it with those options

```
pynonymizer \
    --strategy=$BASEDIR/config.yml \
    --db-host=$DB_HOST \
    --db-port=$DB_PORT \
    --db-user=$DB_USER \
    --db-password=$DB_PW \
    --db-name=$DB_NAME \
    --start-at ANONYMIZE_DB \
    --stop-at ANONYMIZE_DB \
    --verbose
```

So it should not be relying on the ENV var, or? as I'm passing it explicitly

**Comment by jerometwell** [comment]
1. This is a bug, and thank you for the report. this will be fixed in `v1.18.1` which will be released imminently.
2. The "problem" is that your environment vars conflict with pynonymizer's _deprecated_ environment vars. You might not be using them but they're still specified in the environment!

(from CHANGELOG.md)
>  - Deprecated old environment variables in favour of new prefix `PYNONIMIZER_`.
> These will continue to work but will be removed in a future release.
>    - `DB_TYPE -> PYNONYMIZER_DB_TYPE`
>    - `DB_HOST -> PYNONYMIZER_DB_HOST`
>    - `DB_NAME -> PYNONYMIZER_DB_NAME`
>   - `DB_USER -> PYNONYMIZER_DB_USER`
>    - `DB_PASS -> PYNONYMIZER_DB_PASSWORD`
>    - `FAKE_LOCALE -> PYNONYMIZER_FAKE_LOCALE`


If you can't upgrade immediately, as a workaround you can start pynonymizer in a clean env (or change your env args to something else).

**Comment by jerometwell** [comment]
Patch release at https://pypi.org/project/pynonymizer/1.18.1/

**Comment by dmaicher** [comment]
Thanks a lot for fixing it so fast @jerometwell :+1: :tada: 

Just tested it and I can confirm its working again fine.
