### ISSUE TITLE
No way to set sql_require_primary_key=0 for seeding

### ISSUE THREAD

**Issue by leovanhaaren** [jerometwell/pynonymizer#68]
**Describe the bug**
Currently there is no way of setting `sql_require_primary_key` for the database seeding step. For the anonymization step i used the `before` script, but for seeding this is not possible. Is there a way to give this input somewhere or can it be added?

I only see;
```
[MYSQL] pass additional arguments to the
                        restore process (advanced use only!).
                        [$PYNONYMIZER_MYSQL_CMD_OPTS]
```

**To Reproduce**
Use a digitalocean mysql RDB or manually set sql_require_primary_key=1 in a mysql8 database

**Expected behavior**
It would be nice to have a way of settings this variable in the session.

Error:
```
[ANONYMIZE_DB]
creating seed table with 1 columns
ERROR 3750 (HY000) at line 1: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
Traceback (most recent call last):
  File "/usr/local/bin/pynonymizer", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/pynonymizer/cli.py", line 177, in cli
```

**Comment by jerometwell** [comment]
Hi, did you find a solution for this?

**Comment by leovanhaaren** [comment]
@jerometwell Hey, well I thought I had it, but it didnt work, what I tried;

```
PYNONYMIZER_MYSQL_CMD_OPTS: "SET sql_require_primary_key=0;"
```

But this doesnt work unfortunately.

**Comment by leovanhaaren** [comment]
Stupid mistake on my part, it should have been:

```
PYNONYMIZER_MYSQL_CMD_OPTS: --init-command="SET sql_require_primary_key=0;"
```

Now it works!
